# Generated by Django 2.1.7 on 2019-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchCalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchcall',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
