# Generated by Django 2.1.7 on 2019-03-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchCalls', '0003_auto_20190313_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='dispatchCall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='dispatchCalls.DispatchCall'),
        ),
    ]
