# Generated by Django 2.1.7 on 2019-03-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20190311_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
